### ISSUE TITLE
IndexManager is not thread safe

### ISSUE THREAD

**Issue by xwlantian** [amaggiulli/QLNet#205]
## Expected Behavior

IndexManager should be thread safe
## Current Behavior

IndexManager is not thread safe
## Possible Solution

Use concurrent dictionary or lock the current dictionary
## Steps to Reproduce (for bugs)

Use ratehelpers to build YieldTermstructure in multiple-threaded environment

## Your Environment

* Version used ( QLNet 1.10 )
* Environment name and version (.NET Core 2.0 on Windows 7):

**Comment by geobmx540** [comment]
@xwlantian it could be helpful if you could create a sample test that fails

**Comment by imachabeli** [comment]
Hi, I'm having issues with yieldtermstructure in multithreaded environment, "Missing USDLibor3M Actual/360 fixing for 7/23/2018". by the time this error happens Curve is fully built. 
Could you share what kind of exception you get ?

**Comment by Daniel-Svensson** [comment]
QLNet have some severe issues regaring concurrent use due to how the evaluationdate is a single global variable which updates/recalculates all rates/qutes and related yield curves. So currently it seems like you need to take a lock from when you start creating quotes/rates, constructing curves until you have finished with all calculations (all usages of the curves).

It would be really nice if was possible to opt out of this auto update machinery or, use separate non-static settings class for using separate "sessions".

https://github.com/amaggiulli/QLNet/issues/215 seems to be a related issue wich seems to propose a workaround to some of the issues, it might make it possible for cuncurrent use (but still a bit brittle with the user required to handle syncronization)

**Comment by tournierjc** [comment]
Hello,

I think I got it to work (still need some tests, but if you can look on your side as well?).

1) First create Patterns/Singleton.cs:
`/*
 Copyright (C) 2019 Jean-Camille Tournier (jean-camille.tournier@avivainvestors.com)

 This file is part of QLNet Project https://github.com/amaggiulli/qlnet

 QLNet is free software: you can redistribute it and/or modify it
 under the terms of the QLNet license.  You should have received a
 copy of the license along with this program; if not, license is
 available online at <http://qlnet.sourceforge.net/License.html>.

 QLNet is a based on QuantLib, a free-software/open-source library
 for financial quantitative analysts and developers - http://quantlib.org/
 The QuantLib license is available online at http://quantlib.org/license.shtml.

 This program is distributed in the hope that it will be useful, but WITHOUT
 ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 FOR A PARTICULAR PURPOSE.  See the license for more details.
*/

namespace QLNet
{
    //http://msdn.microsoft.com/en-us/library/ff650316.aspx
    public class Singleton<T> where T : class, new()
    {
        private static volatile T instance;
        private static object syncRoot = new object();

        protected Singleton() { }

        public static T Instance
        {
            get
            {
                if (instance == null)
                {
                    lock (syncRoot)
                    {
                        if (instance == null)
                            instance = new T();
                    }
                }
                return instance;
            }
        }
    }
}
`
2) Add these two methods to observablevalue.cs:

`      public static implicit operator ObservableValue<T>(T d)
      {
         ObservableValue<T> r = new ObservableValue<T>();
         r.Assign(d);
         return r;
      }

      public static implicit operator T(ObservableValue<T> d)
      {
         return d.value();
      }
`

3) Modify Settings.cs as follow and remove all static keywords:

`    public class Settings : Singleton<Settings>
    {
        private ObservableValue<Date> evaluationDate_;
        private bool includeReferenceDateEvents_;
        private bool enforcesTodaysHistoricFixings_;
        private bool? includeTodaysCashFlows_;

        public Settings()
        { }
`
4) For Indexes/Indexmanager.cs and Currencies/ExchangeRateManager.cs, do the same inheritance and remove all mention to "instance" (fields, methods, etc.)

5) Update for all .cs files:
`Settings.evaluationDate()` becomes `Settings.Instance.evaluationDate()`
etc.

**Comment by tournierjc** [comment]
Hello Andrea,

Quick comments on your fix:

- Indexes\IndexManager.cs
`data_.TryRemove(name.ToUpper(),out _);`

Will not work for QLNetOld project because C# < 7.0. I suggest:

```
ObservableValue<TimeSeries<double?>> useless;
data_.TryRemove(name.ToUpper(), out useless);
```

- Math\PrimeNumber.cs 
Will probably crash if called on several threads. As a workaround I removed all the static fields except for `firstPrimes` array.

- Pattern\Singleton.cs
I would have appreciate you keeping my name on the top of the file :-)

- Currencies/ExchangeRateManager.cs
Should `ConcurrentDictionary<int, List<Entry>> data_` be  `ConcurrentDictionary<int, SynchronizedCollection<Entry>> data_` instead?

Good idea to use the ConcurrentDictionary, in my implementation I simply "locked" everything and it wasn't very pretty...

**Comment by amaggiulli** [comment]
I don't have a great feeling about these changes, the static code is more hidden but still present...all the machinery as @Daniel-Svensson calls them. I'd rather find a solution like the one described briefly by him , create sessions and get rid of static stuff for Settings, Indexes and ExchangeRates.
Anyway if this pr solve the multi-threading issue and we got positive feedback can be merged.

**Comment by datametrics** [comment]
Hello,
I have tried the MT branch without success, there where still some statics in Settings that caused strange behaviors.

What i now did is:

1) Modify Singleton<T> to use ThreadLocal<T> structure internally:
  `public class Singleton<T> where T : class, new()
   {
      private static ThreadLocal<T> instances = new ThreadLocal<T>(() => new T());
      protected Singleton() { }

      public static T Instance
      {
         get
         {
            return instances.Value;
         }
      }
   }`


2) strictly change all static methods in Settings:
    ` // Observable interface
      private readonly WeakEventSource eventSource = new WeakEventSource();
      public event Callback notifyObserversEvent
      {
         add
         {
            eventSource.Subscribe(value);
         }
         remove
         {
            eventSource.Unsubscribe(value);
         }
      }

      public void registerWith(Callback handler) { notifyObserversEvent += handler; }
      public void unregisterWith(Callback handler) { notifyObserversEvent -= handler; }
      private void notifyObservers()
      {
         eventSource.Raise();
      }

      public void clearObservers()
      {
         eventSource.Clear();
      }`

3) change instrument implementations to use the instance references:

` Settings.Instance.registerWith(update);`



Now i can run concurrent calculations with threadisolated curves at least technically. 
Going forward to investigate the correctness of numbers..

Regards
